stages:
  - test
  - build
  - deploy

variables:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  PATH: "${CARGO_HOME}/bin:${PATH}"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/bin
    - .cargo/registry
    - target/${CARGO_BUILD_TARGET}/release/deps
    - target/${CARGO_BUILD_TARGET}/release/build

before_script:
  - rustup --version || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal --default-toolchain=stable
  - rustup default stable
  - cargo --version
  - rustc --version

test:
  stage: test
  script:
    - cargo clippy
    - cargo test

build:
  stage: build
  script:
    - cargo build --target ${CARGO_BUILD_TARGET} --release
  artifacts:
    paths:
      - target/${CARGO_BUILD_TARGET}/release/${CI_PROJECT_NAME}
    expire_in: 1 week

deploy:
  stage: deploy
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Deploying to production..."
    # Add your deployment commands here
    # e.g. scp target/release/myapp user@server:/path/
  needs: ["build"]
