workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

image: rust:latest

stages:
  - lint
  - test
  - build
  - deploy

variables:
  CARGO_TERM_COLOR: always
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

  # specifically without `CARGO_` prefix in order to `cargo test`
  # to not create `target/x86_64-unknown-linux-gnu` directory
  BUILD_TARGET: x86_64-unknown-linux-gnu

before_script:
  - echo "Cache contents:"; du -sh .cargo target/* || true

after_script:
  - echo "Cache contents:"; du -sh .cargo target/* || true

lint:
  stage: lint
  cache:
    key: debug
    paths:
      - .cargo/registry
      - target/debug
  script:
    - rustup component add clippy
    - cargo clippy

test:
  stage: test
  cache:
    key: debug
    paths:
      - .cargo/registry
      - target/debug
  script:
    - cargo test

build:
  stage: build
  cache:
    key: release
    paths:
      - .cargo/registry
      - target
  script:
    - cargo build --target ${CARGO_BUILD_TARGET} --release
  artifacts:
    paths:
      - target/${CARGO_BUILD_TARGET}/release/${CI_PROJECT_NAME}
    expire_in: 1 week

deploy:
  stage: deploy
  environment: production
  cache: []
  script:
    - echo "Deploying to production..."
    # Add your deployment commands here
    # e.g. scp target/release/myapp user@server:/path/
  needs: ["build"]
